name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt5
      run: sudo apt update && sudo apt install -y qtbase5-dev libqt5sql5-sqlite

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --parallel $(nproc)

    - name: Test
      run: ctest --test-dir build --output-on-failure
